t=(1,2,3,4)
t1=(9,8,7,6)
t2=('a','b','c','d','e')
print("concatination")
print(t+t1)
print("repeatation")
print(t*2)
print("index")
print(t[2])
print("membership")
print(9 in t1)
print(1 not in t1)
print("looping")
for i in t:
	print(i)
print("slicing")
print(t[1:4])
print(t[1:-1])
print(t[::-2])
	
